# Annotation

When you get the peaks table or features table, annotation of the peaks would help you. Check this review[@domingo-almenara2018] for a detailed notes on annotation. They proposed five levels regarding currently computational annotation strategies.

- Level 1: Peak Grouping: MS Psedospectra extraction based on peak shape similarity and peak abundance correlation

- Level 2: Peak Annotation: Adducts, Neutral losses, isotopes, and other mass relationships based on mass distances

- Level 3: Biochemical knowledge based on putative identification, potential biochemical reaction and related statistical analysis 

- Level 4: Use and intergration of tandem MS data based on data dependant/independent acquistion mode or **in silico** predction

- Level 5: Retention time prediction based on library-available retention index or quantitative structure-retnetion relationships (QSRR) models.

Most of the softwares are at level 1 or 2. 

## Issues in annotation

The major issue in annotation is the redundancy peaks from same metabolite. Unlike genomcis, peaks or featuers from peak selection are not independant with each other. Adducts, in-source fragments and isotopes would lead to missannotation. A commen solution is that use known adducts, neutral losses, molecular multimers or multipley charged ions to compare mass distances.

Another issue is about the MS/MS database. Only 10% of known metabolites in databases have experimental spectral data. Thus **in silico** prediction are required. Some works try to fill the gap between experimental data, theoretical values(from chemical database like chemspider) and prediction together. Here is a nice review about MS/MS prediction[@hufsky2014].

## Annotation v.s. identification

According to the defination from the Chemical Analysis Working Group of the Metabolomics Standards Intitvative[@sumner2007;@viant2017]. Four levels of confidence could be assigned to identification:

- Level 1 'identified metabolites'
- Level 2 'Putatively annotated compounds'
- Level 3 'Putatively characterised compound classes'
- Level 4 'Unknown'

In practice, data analysis based annotation could reach level 2. For level 1, we need at extra methods such as MS/MS, retention time, accurate mass, 2D NMR spectra, and so on to confirm the compounds. However, standards are always required for solid proof.
