# Batch effect

## Remove batch effect without optimation for xcms

```{r sva,cache=TRUE,echo=FALSE}
library(faahKO)
source('https://raw.githubusercontent.com/yufree/democode/master/meta/svaplotdefalt.R')
# get the demo data in faahKO packages
path <- system.file("cdf",package = "faahKO")
df <- getopmsdata(path)
lv <- c(rep(1,6),rep(2,6))
svaplot(df,lv)

ddanova <- svaplot(df,lv,pqvalues = 'anova')
ddsa <- svaplot(df,lv,pqvalues = 'sv')

dim(dd)
dim(ddanova)
dim(ddsa)
```


## Remove batch effect without batch information

```{r svao,cache=TRUE,echo=FALSE}
library(faahKO)
source('https://raw.githubusercontent.com/yufree/democode/master/meta/svaplot.R')
# get the demo data in faahKO packages
path <- system.file("cdf",package = "faahKO")
# show the DoE
lv <- gl(2,6)
df <- getdata(path,pmethod='hplcqtof')
dd <- svaplot(df,lv,pqvalues = "sv",scale = F)
dd2 <- svaplot(df,lv,pqvalues = "sv",scale = T)

ddanova <- svaplot(df,lv,pqvalues = 'anova')
ddsa <- svaplot(df,lv,pqvalues = 'sv')

dim(dd)
dim(ddanova)
dim(ddsa)
```

